### ISSUE TITLE
Reconciliation returns wrong item - titles match but DOIs don't

### ISSUE THREAD

**Issue by Dominic-DallOsto** [diegodlh/zotero-cita#138]
**Describe the bug**
I imported [this](https://doi.org/10.15252/msb.202110387) item into Zotero, then tried to find its QID. [This](https://www.wikidata.org/wiki/Q106638260) item was incorrectly returned. The titles match, but the DOIs are different - apparently the paper with an existing QID is an earlier project description paper.

Is this expected behaviour because a preprint might have a different DOI to a published paper? Or should we always check unique identifiers like DOI before matching titles?

To be honest, from a first glance it wasn't clear to me whether the two items were the same - only after closer inspection.

**Environment:**
 - Zotero version: 5.0.96.3
 - Cita version: 0.3.1
 - OS name and version: Windows 10

**Comment by diegodlh** [comment]
> Is this expected behaviour because a preprint might have a different DOI to a published paper? Or should we always check unique identifiers like DOI before matching titles?

As explained [here](https://openrefine-wikibase.readthedocs.io/en/latest/architecture.html), if a DOI or ISBN were provided, "candidates are first fetched by looking for items with the supplied identifiers". If no candidates are found (or if DOI or ISBN were not provided) the query field (i.e., title) is searched for.

Regarding preprints, in my opinion they should be treated differently from the final publication, as expressed [here](https://github.com/diegodlh/zotero-cita/issues/51#issuecomment-816894306).

You posted this issue on Oct 22, 2021 around 8:30 am UTC. According to the [revision history](https://www.wikidata.org/w/index.php?title=Q109071931&offset=&limit=500&action=history) of the correct item (Q109071931), it was created a few hours later. This would explain why you finally got this QID a few days later.

I wonder whether you got an exact match, though. You should have got a partial match because the titles do not match exactly:

- article: COVID19 Disease Map, a computational knowledge repository of virus–host interaction mechanisms
- preprint: COVID-19 Disease Map, a computational knowledge repository of **SARS-CoV-2** virus-host interaction mechanisms

Shall we close this?
