### ISSUE TITLE
Preferences window

### ISSUE THREAD

**Issue by diegodlh** [diegodlh/zotero-cita#35]
Implement preferences window, including:
- [ ] Custom Wikibase instance (other than Wikidata), with custom properties.
- [x] Save citations to note attachments (#13) vs extra field
- [ ] Custom Grobid instance
- [ ] Wikidata credentials (username and password) for edits
- [ ] Default actions the user may have requested to not be asked about again (e.g., delete remote citation as well when deleting local citation with Wikidata OCI)

**Comment by RoBaaaT** [comment]
Hi, thanks for the great extension! It is already really useful, and could be even better with some quality-of-life improvements like automatic actions for new items (#14). I saw that resolving this issue here would be a prerequisite for #14. 

I'd be happy to work on the preference window and then on #14, but I was wondering if you are even currently accepting outside contributions?
Looking at the open pull requests it seems like there is a bit of a backlog?

Cheers
Robert

**Comment by Dominic-DallOsto** [comment]
Hi Robert,

Thanks for your interest!

Yeah, we are backlogged a bit with PRs at the moment, but I'd make it a 
priority to quickly review any contribution you might make. For 
something like a preferences window or automatic actions that should be 
mostly decoupled from the Cita's core functionality, I don't envisage a 
lot of complications arising.

Thanks,
Dom

**Comment by RoBaaaT** [comment]
Hi Dom,

that's great to hear, thanks. I'll try to get the preference window done within the next few weeks.

**Comment by Dominic-DallOsto** [comment]
Amazing!

 From my own setup, Zotfile, Zutilo and MdNotes all have nice 
preferences menus that could be a source of inspiration.

But any other ideas / suggestions you have would be welcome for sure.

**Comment by Dominic-DallOsto** [comment]
I'll close this now - we can make separate issues for the settings we still need to add
